### ISSUE TITLE
Thảo luận về đề tài

### ISSUE THREAD

**Issue by KevilTtc** [CnpmLanKit/SEO3-Group10#1]
Nam vs @NamSukio  Luyện có ý kiến gì nêu thử ae xem sao? t thì thấy mấy ứng dụng nhắc nhở uống nước, đếm bươc chân và ứng dụng đo tốc độ mạng khá hay và tiện cho việc code trong thơi gian ngắn

**Comment by KevilTtc** [comment]
Mấy đứa bàn qua về đề tài nhá. Nhóm mình làm về ứng dụng nhắc nhở uống nước hàng ngày, dựa trên các hoạt động trong ngày mà đưa ra lượng nước cần thiết cho cơ thể người

**Comment by DinhNam99** [comment]
Ừ. Tạo dần bản thiết kế chi tiết cho dễ hình dùng nhỉ?

**Comment by KevilTtc** [comment]
[App-Nhắc-nhở-uống-nước.docx](https://github.com/CnpmLanKit/SEO3-Group10/files/3781170/App-Nh.c-nh.-u.ng-n.c.docx)
Đây là bản thiết kế nhé, ae tham khảo qua xem chỗ nào chưa hợp lý thì đóng góp ý kiến nhé.

**Comment by TuanAnhID1999** [comment]
Thế mình bây giờ làm dự án App nhắc nhở uống nước nhé , hay ae có ý tưởng gì không nói thử xem?

**Comment by DinhNam99** [comment]
Ok.

**Comment by TuanAnhID1999** [comment]
Ok thế chốt làm ứng dụng nhắc nhở uống nước nhé. T cũng đang ngồi cạnh với Luyện nên ae chốt rồi nhé.

**Comment by KhacLuyen99** [comment]
Ok , chốt ứng dụng Nhắc nhở uống nước. Sáng mai ae thảo luận rồi triển khai luôn

**Comment by KevilTtc** [comment]
Ok, thế h t đóng cmt này lại.
